version: "3"

services:
  ##########################################
  # Overrides for oada-core services:
  ##########################################

  # Add ourselves to yarn to do yarn install
  yarn:
    volumes:
      - ./services-available/trellis-masker:/code/trellis-masker

  # Add ourselves to admin container:
  admin:
    volumes:
      - ./services-available/trellis-masker:/code/trellis-masker


  ###############################################
  # This service's definition:
  ###############################################
  trellis-masker:
    build:
      context: ./services-available/trellis-masker
    container_name: trellis-masker
    restart: always
    networks:
      - http_net
    volumes:
      - ./services-available/trellis-masker:/code/trellis-masker
      - ./oada-core/libs:/code/libs
      - ./oada-srvc-docker-config.js:/oada-srvc-docker-config.js
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-*info*,*warn*,*error*}
      - domain
      - token
